# This file was generated by GoReleaser. DO NOT EDIT.
cask "dbprompter" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "46a7e24f35908b46adc626b083bc2715c5cdfb3fc2cda556905f524de6c940c8"
      url "https://github.com/adharshmk96/dbprompter/releases/download/v#{version}/dbprompter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bb2e321e631ecd7137c6d0fca70dd1e03559b42a13930d9fabdab0b08de93c2e"
      url "https://github.com/adharshmk96/dbprompter/releases/download/v#{version}/dbprompter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "52440af91bcfe70bd173e7ec843d8f6c3ab06318cc4d0af4215c72a0ecb9b401"
      url "https://github.com/adharshmk96/dbprompter/releases/download/v#{version}/dbprompter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bbc09ed1781476c8fa08578b4d08191d84cc758de5dea240aab03c09b37bb1b6"
      url "https://github.com/adharshmk96/dbprompter/releases/download/v#{version}/dbprompter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dbprompter"
  desc "Explore any database and query it with AI"
  homepage "https://github.com/adharshmk96/dbprompter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dbprompter"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dbprompter"]
    end
  end

  # No zap stanza required

end
