# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver" do
  version "1.4.3"

  on_macos do
    on_intel do
      sha256 "b9728e16a2ffa46471c524c6cafed8224460a9e71705cc39843fbc077ac54b1d"
      url "https://github.com/adharshmk96/semver/releases/download/v#{version}/semver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0dd465455de31502281b7afea24f6c53b7391346945311061d1e1450de29bef4"
      url "https://github.com/adharshmk96/semver/releases/download/v#{version}/semver_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6cbebebb2ebfe117431153f8c317c40e327051fa3853ac87aa7bd94d0e02f9f1"
      url "https://github.com/adharshmk96/semver/releases/download/v#{version}/semver_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "41f9cddc56d2755f060fa0c19b7225f4f134ff16925f0f634a69c401af860e67"
      url "https://github.com/adharshmk96/semver/releases/download/v#{version}/semver_#{version}_linux_arm64.tar.gz"
    end
  end

  name "semver"
  desc "Semantic version management CLI for git tags and .version files"
  homepage "https://github.com/adharshmk96/semver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semver"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/semver"]
    end
  end

  # No zap stanza required

end
