# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver" do
  version "1.4.2"

  on_macos do
    on_intel do
      sha256 "3e7ef1fb3ea5747a4051d2d944cd1df31204e35f3a5e905b4fe2af63971520e5"
      url "https://github.com/adharshmk96/semver/releases/download/v#{version}/semver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "552b4508f83d651bf495d933cadd9991d51fe2f473dd5035638f6aa4a83cba5c"
      url "https://github.com/adharshmk96/semver/releases/download/v#{version}/semver_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "77ca28756272c209b21b656be1c25ed119bf33ea17693f09f1e4b9f52df9556e"
      url "https://github.com/adharshmk96/semver/releases/download/v#{version}/semver_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "033f21933d29397beb8c4f073814a28a0318148cd74393f9a38ff6df7662f3fa"
      url "https://github.com/adharshmk96/semver/releases/download/v#{version}/semver_#{version}_linux_arm64.tar.gz"
    end
  end

  name "semver"
  desc "Semantic version management CLI for git tags and .version files"
  homepage "https://github.com/adharshmk96/semver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semver"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/semver"]
    end
  end

  # No zap stanza required

end
