# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver" do
  version "1.4.4"

  on_macos do
    on_intel do
      sha256 "a9467582311da7de44b96c5d49235bca8234f5c69ae0a34f36decbd0cbfa494f"
      url "https://github.com/adharshmk96/semver/releases/download/v#{version}/semver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1ba5592c5c05fdf0ece0746c48d7d2d15d94297febfc17a51001d530da96bcae"
      url "https://github.com/adharshmk96/semver/releases/download/v#{version}/semver_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "37f07f9a8e5609d299449991f0b016742c7703eab0fbc37f40382d8ca135e597"
      url "https://github.com/adharshmk96/semver/releases/download/v#{version}/semver_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "916b99c6a42733ad9eaebde3fb6a262ddcc2d7c4cf578dff8d341d134ff6f19a"
      url "https://github.com/adharshmk96/semver/releases/download/v#{version}/semver_#{version}_linux_arm64.tar.gz"
    end
  end

  name "semver"
  desc "Semantic version management CLI for git tags and .version files"
  homepage "https://github.com/adharshmk96/semver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semver"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/semver"]
    end
  end

  # No zap stanza required

end
