# This file was generated by GoReleaser. DO NOT EDIT.
cask "vugit" do
  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "09b40b51008a01d04e4993889587a555c6d075b5cac24b6c27fe7ac5d61f5400"
      url "https://github.com/adharshmk96/vugit/releases/download/v#{version}/vugit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7c10fee856a11c4ca58b81d7667d5af3d6a3b4df6518eec0cc37f9fa4cd1fc9d"
      url "https://github.com/adharshmk96/vugit/releases/download/v#{version}/vugit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ea4735da29cf3c281c0a17a66e23755f1725d090b088cfa1dc8122c4eab29e46"
      url "https://github.com/adharshmk96/vugit/releases/download/v#{version}/vugit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8149066225b0c2a9f3d1b491638a821c9c1aacef5269d967687b76615df221be"
      url "https://github.com/adharshmk96/vugit/releases/download/v#{version}/vugit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vugit"
  desc "Version management CLI for git projects"
  homepage "https://github.com/adharshmk96/vugit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vugit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vugit"]
    end
  end

  # No zap stanza required
end
