# This file was generated by GoReleaser. DO NOT EDIT.
cask "vugit" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "983be2d8562425fc7fd0f7ddb1c70ed992254e2d4f59465429494c167448d3f4"
      url "https://github.com/adharshmk96/vugit/releases/download/v#{version}/vugit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2acf967ef78d13dff623f6bb85e7afeca259f2f6164d0caa97acef5f7d9ef583"
      url "https://github.com/adharshmk96/vugit/releases/download/v#{version}/vugit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b77980962a120fe292aeccc2d8ff789036b2f2ec68726c443b383a74c405ad9a"
      url "https://github.com/adharshmk96/vugit/releases/download/v#{version}/vugit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d430d732861ad7e6eadce2f1e5ad84327c14fa24bb49a5e5a6b04cf209592242"
      url "https://github.com/adharshmk96/vugit/releases/download/v#{version}/vugit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vugit"
  desc "Version management CLI for git projects"
  homepage "https://github.com/adharshmk96/vugit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vugit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vugit"]
    end
  end

  # No zap stanza required
end
